product_routes:
    path: module_test/demo
    methods: [GET]
    defaults:
      _controller: 'ModuleTest\Controller\Admin\DemoController::demoAction'
      _legacy_controller: DemoController
      _legacy_link: DemoController
      
      
      